<?php
/*
    Coded by Jon Borglund 2005 - 2008

    Your API Key is XXX and your secret is XXX

    last.fm url

*/
set_time_limit(0);
/*error_reporting(E_ALL);*/
function stripslashes_array($data) {
   //Om det är en array
   if (is_array($data)){
       foreach ($data as $key => $value){
           $data[$key] = stripslashes_array($value);
       }
       return $data;
   }else{
       return stripslashes($data);
   }
}
if (get_magic_quotes_gpc()) {
    $_POST = stripslashes_array($_POST);
    $_GET = stripslashes_array($_GET);
}
function __autoload($class_name)
{
    require_once 'class/' . $class_name . '.class.php';
}

if(isset($_POST['tracks'])) {
    $user = isset($_POST['user']) ? $_POST['user'] : 'unknown';
    $type = isset($_POST['type']) ? $_POST['type'] : 0;

    switch($type) {
    case lastXMLtoArray::TYPE_USERWEEKLY:
        $shortname = 'lstfm_usr_wkl_' . $user;
        break;
    case lastXMLtoArray::TYPE_USERLOVED:
        $shortname = 'lstfm_usr_lov_' . $user;
        break;
    case lastXMLtoArray::TYPE_TAGTOP:
        $shortname = 'lstfm_tag_top_' . $user;
        break;
    case lastXMLtoArray::TYPE_GROUPWEEKLY:
        $shortname = 'lstfm_grp_wkl_' . $user;
        break;
    default:
        $shortname = 'lstfm_usr_top_' . $user;
        break;
    }
    $lpl = "#EXTM3U\r\n#File generated by Rowolta's M3U generator http://lastm3u.powha.net " . date('Y-m-d H:i:s') . "\r\n".implode("\r\n",$_POST['tracks']);
    header('Pragma: public');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Cache-Control: private',false);
    header('Content-Type: audio/x-mpegurl');
    header('Content-Disposition: attachment; filename="'.$shortname.'.m3u"');
    header('Content-Transfer-Encoding: binary');
    header('Content-Length: ' . strlen($lpl));
    echo $lpl;
    die();
}
if(isset($_REQUEST['user']) && isset($_REQUEST['type'])) {
    $pl = new lastm3u($_FILES['m3u']['tmp_name']);
    try
    {
        $pl->load($_REQUEST['user'], $_REQUEST['type']);
        echo '<script type="text/javascript">window.parent.m3uPrepare('.
              json_encode(array(
              "found" => $pl->getFound(),
              "notfound" => $pl->getNotFound())).
              ');</script>';
    } catch (Exception $e) {
        echo '<script type="text/javascript">window.parent.m3uPrepare('.
              json_encode(array(
              "error" => $e->getMessage())).
              ');</script>';
    }

    die();
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>LAST.FM - Chart to M3U Playlist Generator :: By Rowolta BETA</title>
<script type="text/javascript" src="http://js.powha.net/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="js/lastm3u.js"></script>
<link href="style.css" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="/favicon.png" />
</head>
<body>
<div id="wrapper">
        <div id="header"><h1>LAST.FM - Chart to M3U Playlist Generator <sup>v2.0</sup></h1></div>
        <p>The purpose of this application is to find tracks from the selected chart in your m3u-file-contents and generate a new one. Questions and comments can be sent to me at my last.fm <a href="http://www.last.fm/user/rowolta">profile</a></p>

        <p class="info">In Windows you can generate a m3u (filelist) with this batch command.<br /><strong>dir *.mp3 *.ogg *.wma *.ape /b /s > my_audio_files.txt</strong></p>

    <div id="form">
        <form method="post" action="" enctype="multipart/form-data" target="lastUpload" id="lastform">
           <table>
               <tr>
                    <td><label for="type">Select target</label></td>
                    <td><select id="type" name="type" title="Select user, group or tag">
                            <option value="false">User, group or tag</option>
                            <optgroup label="User">
                                <option value="0">Top Tracks</option>
                                <option value="2">Weekly Top Tracks</option>
                                <option value="1">Loved Tracks</option>
                            </optgroup>
                            <optgroup label="Group">
                                <option value="3">Weekly Top Tracks</option>
                            </optgroup>
                            <optgroup label="Tag">
                                <option value="4">Top Tracks</option>
                            </optgroup>
                        </select>
                    </td>
               </tr>
               <tr>
                    <td><label for="user" id="label">User, tag or group</label></td>
                    <td><input type="text" name="user" id="user" /></td>
               </tr>
               <tr>
                    <td><label for="file">M3U file</label></td>
                    <td><input id="file" type="file" name="m3u" /></td>
               </tr>
               <tr>
                       <td>&nbsp;</td>
                    <td><input type="submit" value="Process" /></td>
               </tr>
           </table>

        </form>
     </div>
     <div id="loader"></div>
     <div id="varning">
         <p id="varningInfo"></p>
        <input type="button" id="varningButton" value="Close"/>
     </div>
    <div id="resultBox">
        <form method="post" target="lastUpload" action="">
            <p>Unselect tracks that you don't want to include in the final m3u. When done click "Generate new m3u"</p>
            <input type="submit" value="Generate new M3U" /><input type="button" value="Start over" id="reset" />
            <h2>Found in your m3u-playlist</h2>
            <ol id="found"></ol>
        </form>
        <h2>Not found in your m3u-playlist</h2>
        <ol id="notfound"></ol>
    </div>
    <div id="footer">&copy;2009 <a href="http://www.last.fm/user/rowolta">Rowolta</a> CSS | XHTML | JavaScript</div>
</div>
<iframe src="about:blank" name="lastUpload" id="lastUpload"></iframe>
</body>
</html>
